"""Deterministic (de)serialization of provider pricing files.

The JSON layout is canonical: models are sorted by id, price sets by their
conditions/threshold/date, rates follow dimension-registry order, and decimals
are written as plain strings (never floats, never exponents).  Serializing the
same data therefore always yields byte-identical output, which keeps generated
data diffs minimal and reviewable.
"""

from __future__ import annotations

import json
from datetime import date
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

from .dimensions import DIMENSIONS
from .errors import CatalogValidationError
from .model import ModelPricing, PriceSet, ProviderPricing, Source
from .validation import validate_provider

SCHEMA_VERSION = 1
GENERATED_NOTICE = (
    "Generated by `openai-cost-calculator pricing sync`. Edit the source parsers or "
    "curated tables under openai_cost_calculator/sync/, not this file."
)

_DIMENSION_ORDER = {name: index for index, name in enumerate(DIMENSIONS)}


def format_decimal(value: Decimal) -> str:
    """Render a Decimal as a plain, minimal string (``Decimal('2.50')`` -> ``'2.5'``)."""
    text = format(value.normalize(), "f")
    return "0" if text in ("-0", "") else text


def _parse_decimal(value: Any, where: str) -> Decimal:
    if isinstance(value, bool) or not isinstance(value, (str, int)):
        raise CatalogValidationError(f"{where}: price must be a decimal string, got {value!r}")
    try:
        return Decimal(str(value))
    except InvalidOperation as exc:
        raise CatalogValidationError(f"{where}: invalid decimal {value!r}") from exc


def _parse_date(value: Any, where: str) -> Optional[date]:
    if value is None:
        return None
    if not isinstance(value, str):
        raise CatalogValidationError(f"{where}: dates must be 'YYYY-MM-DD' strings")
    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise CatalogValidationError(f"{where}: invalid date {value!r}") from exc


def _require(mapping: Mapping[str, Any], key: str, kind: type, where: str) -> Any:
    value = mapping.get(key)
    if not isinstance(value, kind):
        raise CatalogValidationError(f"{where}: {key!r} must be a {kind.__name__}")
    return value


def _parse_price_set(raw: Any, where: str) -> PriceSet:
    if not isinstance(raw, dict):
        raise CatalogValidationError(f"{where}: price set must be an object")
    unknown = set(raw) - {"rates", "conditions", "min_input_tokens", "effective_from", "effective_until"}
    if unknown:
        raise CatalogValidationError(f"{where}: unknown price-set keys {sorted(unknown)}")
    rates_raw = _require(raw, "rates", dict, where)
    conditions = raw.get("conditions") or {}
    if not isinstance(conditions, dict):
        raise CatalogValidationError(f"{where}: 'conditions' must be an object")
    return PriceSet(
        rates={str(k): _parse_decimal(v, f"{where}.rates.{k}") for k, v in rates_raw.items()},
        conditions={str(k): v for k, v in conditions.items()},
        min_input_tokens=raw.get("min_input_tokens", 0),
        effective_from=_parse_date(raw.get("effective_from"), where),
        effective_until=_parse_date(raw.get("effective_until"), where),
    )


def _parse_model(raw: Any, where: str) -> ModelPricing:
    if not isinstance(raw, dict):
        raise CatalogValidationError(f"{where}: model entry must be an object")
    model_id = _require(raw, "id", str, where)
    where = f"{where} ({model_id})"
    prices_raw = _require(raw, "prices", list, where)
    aliases = raw.get("aliases") or []
    if not isinstance(aliases, list) or not all(isinstance(a, str) and a for a in aliases):
        raise CatalogValidationError(f"{where}: 'aliases' must be a list of strings")
    return ModelPricing(
        id=model_id,
        prices=tuple(_parse_price_set(p, f"{where}.prices[{i}]") for i, p in enumerate(prices_raw)),
        source=_require(raw, "source", str, where),
        vendor=raw.get("vendor"),
        canonical_id=raw.get("canonical_id"),
        display_name=raw.get("display_name"),
        aliases=tuple(aliases),
        status=raw.get("status", "active"),
    )


def provider_from_dict(raw: Any, *, where: str = "pricing data") -> ProviderPricing:
    if not isinstance(raw, dict):
        raise CatalogValidationError(f"{where}: top level must be an object")
    version = raw.get("schema_version")
    if version != SCHEMA_VERSION:
        raise CatalogValidationError(f"{where}: unsupported schema_version {version!r} (expected {SCHEMA_VERSION})")
    provider = _require(raw, "provider", str, where)
    sources = tuple(
        Source(
            id=_require(s, "id", str, f"{where}.sources"),
            kind=_require(s, "kind", str, f"{where}.sources"),
            url=_require(s, "url", str, f"{where}.sources"),
            description=s.get("description", ""),
        )
        for s in _require(raw, "sources", list, where)
    )
    models = tuple(_parse_model(m, f"{where}.models[{i}]") for i, m in enumerate(_require(raw, "models", list, where)))
    data = ProviderPricing(
        provider=provider,
        sources=sources,
        models=models,
        currency=raw.get("currency", "USD"),
        verified_at=_parse_date(raw.get("verified_at"), where),
    )
    validate_provider(data)
    return data


def load_provider_file(path: Path) -> ProviderPricing:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise CatalogValidationError(f"{path}: invalid JSON: {exc}") from exc
    return provider_from_dict(raw, where=str(path.name))


def _price_set_sort_key(price_set: PriceSet) -> tuple:
    return (
        price_set.condition_key,
        price_set.min_input_tokens,
        price_set.effective_from or date.min,
    )


def _price_set_to_dict(price_set: PriceSet) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    if price_set.conditions:
        out["conditions"] = dict(sorted(price_set.conditions.items()))
    if price_set.min_input_tokens:
        out["min_input_tokens"] = price_set.min_input_tokens
    if price_set.effective_from is not None:
        out["effective_from"] = price_set.effective_from.isoformat()
    if price_set.effective_until is not None:
        out["effective_until"] = price_set.effective_until.isoformat()
    out["rates"] = {
        name: format_decimal(price_set.rates[name])
        for name in sorted(price_set.rates, key=lambda n: _DIMENSION_ORDER.get(n, len(_DIMENSION_ORDER)))
    }
    return out


def _model_to_dict(model: ModelPricing) -> Dict[str, Any]:
    out: Dict[str, Any] = {"id": model.id}
    for key in ("display_name", "vendor", "canonical_id"):
        value = getattr(model, key)
        if value:
            out[key] = value
    if model.aliases:
        out["aliases"] = sorted(model.aliases)
    if model.status != "active":
        out["status"] = model.status
    out["source"] = model.source
    out["prices"] = [_price_set_to_dict(p) for p in sorted(model.prices, key=_price_set_sort_key)]
    return out


def provider_to_dict(data: ProviderPricing) -> Dict[str, Any]:
    return {
        "_notice": GENERATED_NOTICE,
        "schema_version": SCHEMA_VERSION,
        "provider": data.provider,
        "currency": data.currency,
        "verified_at": data.verified_at.isoformat() if data.verified_at else None,
        "sources": [
            {"id": s.id, "kind": s.kind, "url": s.url, **({"description": s.description} if s.description else {})}
            for s in sorted(data.sources, key=lambda s: s.id)
        ],
        "models": [_model_to_dict(m) for m in sorted(data.models, key=lambda m: m.id)],
    }


def dump_provider(data: ProviderPricing) -> str:
    validate_provider(data)
    return json.dumps(provider_to_dict(data), indent=2, ensure_ascii=False) + "\n"


def write_provider_file(path: Path, data: ProviderPricing) -> None:
    path.write_text(dump_provider(data), encoding="utf-8")


def load_directory(directory: Path) -> List[ProviderPricing]:
    return [load_provider_file(path) for path in sorted(directory.glob("*.json"))]
